"""Fix ChatHistory model

Revision ID: 1c9771b85e2c
Revises: 81b210894603
Create Date: 2025-02-10 12:30:52.183163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c9771b85e2c'
down_revision: Union[str, None] = '81b210894603'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_history', sa.Column('model_used', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_history', 'model_used')
    # ### end Alembic commands ###
